### ISSUE TITLE
HMul のタイポ

### ISSUE THREAD

**Issue by Seasawher** [aconite-ac/theorem_proving_in_lean4#14]
> これは、Hmul α α α のインスタンスを実装し、HMul Nat α α のインスタンスは実装しなかった場合に特に重要である。ここで、Leanにおいて表記 a*b がどう定義されているかを種明かしする。

see: https://aconite-ac.github.io/theorem_proving_in_lean4_ja/type_classes.html#default-instances-%E3%83%87%E3%83%95%E3%82%A9%E3%83%AB%E3%83%88%E3%82%A4%E3%83%B3%E3%82%B9%E3%82%BF%E3%83%B3%E3%82%B9

HMul ではないですか

**Comment by aconite-ac** [comment]
ご指摘ありがとうございます。
明らかな誤りですので修正いたします。
