### ISSUE TITLE
依存積型→依存和型

### ISSUE THREAD

**Issue by Seasawher** [aconite-ac/theorem_proving_in_lean4#15]
> 同様に、依存積型 (a : α) × β a は直積型 α × β を一般化する。依存積型は β が a に依存することを可能にする。依存積型はsigma(Σ)型とも呼ばれ、(a : α) × β a は Σ a : α, β a とも書かれる。Leanにおいて、⟨a, b⟩ あるいは Sigma.mk a b と書くと依存ペアを作ることができる。⟨ は \langle または \< と打つと入力でき、⟩ は \rangle または \> と打つと入力できる。

at https://aconite-ac.github.io/theorem_proving_in_lean4_ja/dependent_type_theory.html?highlight=%E4%BE%9D%E5%AD%98%E7%A9%8D%E5%9E%8B#what-makes-dependent-type-theory-dependent-%E4%BD%95%E3%81%8C%E4%BE%9D%E5%AD%98%E5%9E%8B%E7%90%86%E8%AB%96%E3%82%92%E4%BE%9D%E5%AD%98%E3%81%9F%E3%82%89%E3%81%97%E3%82%81%E3%81%A6%E3%81%84%E3%82%8B%E3%81%AE%E3%81%8B

依存積ではなくて依存和では？

**Comment by aconite-ac** [comment]
ご指摘ありがとうございます。
これについては今まで完全に勘違いしておりました。失礼いたしました……。
関数型や直積型の依存型を用いた一般化とみなすことで、パイ型には依存関数型、シグマ型には依存直積型という名称が与えられる一方で、例えば型を有限集合とみなしたときの元の個数を考えることで、パイ型には依存積型、シグマ型には依存和型という名称を与えることもできるのですね。
明確な誤りですので、修正いたします。
